version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: test

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
      - redis
    environment:
      NODE_ENV: production
